### ISSUE TITLE
Can't get the 4K download link

### ISSUE THREAD

**Issue by smsourov** [jtcheng/bing-wallpaper#1]
How do you get the 4K download link?
I tried but the link gives me a 1080p image link.

**Comment by jtcheng** [comment]
@SMSourov:
The `4k` link here not mean `4k` image, just the default image link without any parameters in image url:
such as:
for 4k image link: 
`https://cn.bing.com/th?id=OHR.Invergarry_EN-US5187949443_UHD.jpg`
for small image link:
`https://cn.bing.com/th?id=OHR.Invergarry_EN-US5187949443_UHD.jpg&pid=hp&w=384&h=216&rs=1&c=4`

Sorry for this confuse to you.

**Comment by smsourov** [comment]
@jtcheng Thank you for your reply. You can close this issue.
